apiVersion: apps/v1

kind: Deployment

metadata:
  name: wishlist-api

spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: wishlist-api
  template:
    metadata:
      labels:
        app: wishlist-api
    spec:
      initContainers:
        {{- include "keycloak.init-container" . | nindent 8 }}
          name: wishlist-api-wait-for-sso
      containers:
        - name: api
          image: {{ .Values.api.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: api-configmap
            - configMapRef:
                name: api-configmap-database
            - configMapRef:
                name: api-configmap-keycloak
