apiVersion: v1

kind: Service

metadata:
  name: wishlist-api
  
spec:
  selector:
    app: wishlist-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: {{ .Values.api.port }}
  type: ClusterIP
